### ISSUE TITLE
Steering Committee updates for 2021

### ISSUE THREAD

**Issue by vmbrasseur** [todogroup/governance#100]
## Who/what?

Newly elected:

* Stormy Peters
* Dawn Foster 

Appointed:

* Stephen Jacobs

## Information to gather or verify

- [x] GitHub ID of any new steering committee member(s)
- [x] Email address of any new steering committee member(s)

## Things to update

- [x] [README](https://github.com/todogroup/governance/blob/master/README.md) on the governance repo
- [x] Update the SC member list on the [resolution template](https://github.com/todogroup/governance/blob/master/resolutions/template/standard.md)
- [x] `collaborators` array in [settings.yml](https://github.com/todogroup/governance/blob/master/.github/settings.yml)
- [x] [steering-committee team](https://github.com/orgs/todogroup/teams/steering-committee) on the TODO Group GitHub organization
- [ ] Update the Steering Committee email alias on GSuite (LF staff will need to do this one)
- [ ] Steering Committee meeting calendar invite

**Comment by amye** [comment]
The Steering Committee has voted to appoint @itprofjacobs. Updating this issue.

**Comment by amye** [comment]
@caniszczyk: I think the only one I can't get is: 
[ ] Update the Steering Committee email alias on GSuite (LF staff will need to do this one)

**Comment by geekygirldawn** [comment]
I think this one looks like it's probably done. Feel free to re-open it if not :)
