### ISSUE TITLE
[Strategic Goal] Build a process for the TODO Group Members to file new Initiatives/Ideas and be reviewed by SC

### ISSUE THREAD

**Issue by anajsana** [todogroup/governance#111]
Build a process for those scenarios where the community wants to notify a proposal related to new TODO initiatives (For instance: partnerships with other communities with specific outcomes, working groups which the main purpose is to work on initiatives that do not exist on TODO resources, feedback on existing TODO procedures).

**Existing method**: Resolution repo

**Alternatives**

- Build a proposal issue form: https://github.com/todogroup/governance/pull/156
- Use GH Discussions and use `proposal` tag 

**Action Items**

(1) Decide to either keep working on the proposal form (1.1), discard it and work on the existing resolution repo (1.2), use GH Discussions (1.3)

* (1.1) If keep working on the proposal form then review https://github.com/todogroup/governance/pull/156 (by someone from SC), merge changes, and create necessary documentation

* (1.2) If discard it and work on the existing resolution repo then update [Resolution's README.md](https://github.com/todogroup/governance/blob/main/resolutions/README.md), send a PR with changes, review by the SC, and merge. 

* (1.3) Use the Discussions feature to let the community submit proposals

**Comment by DuaneOBrien** [comment]
I think if we want something like this to be successful, we should be clear with ourselves and with the TODO members about what kinds of things would be appropriate to bring up to the Steering Committee. We should supplement this with some guidelines or examples of the kinds of ideas that would follow this process, and the kinds of ideas that wouldn't.

**Comment by anajsana** [comment]
Thanks for the feedback @DuaneOBrien . One idea that comes to my mind is to have a designated repo for this: https://github.com/todogroup/ideas where we could specify:

* What is this repo for: A collection of ideas to propose new TODO initiatives and programs. Existing ideas should appear on the repo issues page

* Desired format to submit an idea: Create a template that specifies the desired title, goal, description, effort and action items required. The idea would be counted as valid only if those fields are completed

* Election process: expected time that the issues will be open for other TODO members to vote and discuss them (not more than 2 weeks) and how the most voted issues will be passed for the SC to be reviewed (the revision will take place during the SC meeting calls)

* What happens if an idea is rejected by the SC: the issue is closed and the reason is documented.

* What happens if an idea is approved by the SC: the issue keeps open until the idea can be initiated and added to the [kanban board](https://github.com/todogroup/todogroup.org/projects/1)


Comments, thoughts? 🙂

**Comment by geekygirldawn** [comment]
I like this approach and @anajsana's steps, but I'm not sure if we need a separate repo for this? What if we asked people to create these as issues in the Governance repo? We could even implement the proposals template as an issue template to make it easier for people to complete and have it auto-populate it with a "proposals" tag. 

Note: I prefer naming this "proposals" rather than "ideas", but I could go with either

**Comment by anajsana** [comment]
+1 on using the governance repo and call them "Proposals". BTW, I've just realized we have a great discussions space in the governance repo where we can start the initial discussions and election process by the TODO Community prior to the SC review: https://github.com/todogroup/governance/discussions/landing

**Comment by anajsana** [comment]
Based on @geekygirldawn suggestion about asking people to create these as issues. I think we can create a GH issue form for this similar to what we have for OSPOlogy CFP, now that this feature is available (https://github.com/todogroup/ospology/issues/new/choose)

**Comment by anajsana** [comment]
This is the PR where you can see the proposed issue form: https://github.com/todogroup/governance/blob/acb401ce3d33a08585c25b9adc30fea10ef1cd63/.github/ISSUE_TEMPLATE/proposals.yml

**Comment by justaugustus** [comment]
From @DuaneOBrien in https://github.com/todogroup/governance/issues/111#issuecomment-964685387:

> I think if we want something like this to be successful, we should be clear with ourselves and with the TODO members about what kinds of things would be appropriate to bring up to the Steering Committee. We should supplement this with some guidelines or examples of the kinds of ideas that would follow this process, and the kinds of ideas that wouldn't.

and @geekygirldawn in https://github.com/todogroup/governance/pull/156#issuecomment-1005453937:

> I think we need some additional text at the top to give people some guidance about what types of proposals need to go in front of the SC. For example, a proposal for a new guide, case study, or tool would go elsewhere and not need to go to the SC. Wouldn't this be limited to new initiatives or new programs that would be driven by the TODO Group, while any proposal related to an existing program or initiative would be a regular in the repo already existing for that program or initiative?

Strong +1 to framing what rises to level of a proposal requiring Steering review/approval. This guidance should be committed to the repo and referenced in templates/elsewhere (that way it's consistent irrespective of when the request was opened).

> BTW, I've just realized we have a great discussions space in the governance repo where we can start the initial discussions and election process by the TODO Community prior to the SC review: https://github.com/todogroup/governance/discussions/landing

I was coming here to say this.

Suggestions:

- Add guidance to the repo on the proposal and review process
- Use the built-in GitHub Discussions feature
- Label GH Discussions to indicate proposal state
  
  Example:

  - unlabeled: new and untriaged
  - status/ack: SC has ACK-ed proposal
  - status/in-review: SC is actively reviewing
  - status/{approved,rejected,blocked}: SC sets status after review
- Open a formal issue to action on proposal

There should also be some gates to help us conserve monthly meeting time / encourage async operations.

Examples:

- Idea must be sent to the mailing list with a link to GH Discussion
- Idea must be upvoted by at least 1(?) non-SC member to get SC triage
- Idea must be upvoted by at least 2(?) SC members to get on the SC monthly agenda

**Comment by anajsana** [comment]
> From @DuaneOBrien in [#111 (comment)](https://github.com/todogroup/governance/issues/111#issuecomment-964685387):
> 
> > I think if we want something like this to be successful, we should be clear with ourselves and with the TODO members about what kinds of things would be appropriate to bring up to the Steering Committee. We should supplement this with some guidelines or examples of the kinds of ideas that would follow this process, and the kinds of ideas that wouldn't.
> 
> and @geekygirldawn in [#156 (comment)](https://github.com/todogroup/governance/pull/156#issuecomment-1005453937):
> 
> > I think we need some additional text at the top to give people some guidance about what types of proposals need to go in front of the SC. For example, a proposal for a new guide, case study, or tool would go elsewhere and not need to go to the SC. Wouldn't this be limited to new initiatives or new programs that would be driven by the TODO Group, while any proposal related to an existing program or initiative would be a regular in the repo already existing for that program or initiative?
> 
> Strong +1 to framing what rises to level of a proposal requiring Steering review/approval. This guidance should be committed to the repo and referenced in templates/elsewhere (that way it's consistent irrespective of when the request was opened).
> 
Maybe an Action Item should be submitting a PR that creates a `governance.md` file that documents what issues are expected in this repo (e.g new proposals) and how issues are going to be treated and accepted by the Steering Commitee?

I would also like to document what happens if a proposal is ignored by all the SC Commitee members within the expected review period (that we have to document aswell) + make a clear description of what is a new proposal. For instance:

Somethign is a new proposal at TODO project when the desired initiative doesn't fit in the TODO Strategic Goals and/or the existing TODO initiatives (e.g OSPO Survey, OSPO Landscape, OSPO Use Cases, TODO Guides, etc). Examples of new proposals are:

* Creating a new Working Group
* Starting a new community meeting
* Proposing a new partership

> > BTW, I've just realized we have a great discussions space in the governance repo where we can start the initial discussions and election process by the TODO Community prior to the SC review: https://github.com/todogroup/governance/discussions/landing
> 
> I was coming here to say this.
> 
> Suggestions:
> 
>     * Add guidance to the repo on the proposal and review process
> 
>     * Use the built-in GitHub Discussions feature
> 
>     * Label GH Discussions to indicate proposal state
>       Example:
>       
>       * unlabeled: new and untriaged
>       * status/ack: SC has ACK-ed proposal
>       * status/in-review: SC is actively reviewing
>       * status/{approved,rejected,blocked}: SC sets status after review
> 
>     * Open a formal issue to action on proposal
> 

LGTM, but why using two channels (GH Discussions and issues)? I think is simple to make a proposal using only one. For instance, the issue channel (that can take the shape of a form like: https://github.com/todogroup/governance/pull/156/files) and apply the labels you suggested to indicate prosal state. Then, if the issue is approved, close the initial one with a comment that contains the new issue to action on proposal
> 
> There should also be some gates to help us conserve monthly meeting time / encourage async operations.
> 
> Examples:
> 
>     * Idea must be sent to the mailing list with a link to GH Discussion
> 

+1, but as mentioned earlier, I'd suggest to turn this into an issue instead of a GH discussion 

>     * Idea must be upvoted by at least 1(?) non-SC member to get SC triage
> 
>     * Idea must be upvoted by at least 2(?) SC members to get on the SC monthly agenda

**Comment by vmbrasseur** [comment]
It looks like a great deal of work has been done on this already by the 2021 SC (thank you!).

My primary question here is how do Proposals differ from the already existing [Resolutions](https://github.com/todogroup/governance/blob/main/resolutions/README.md)? How to we clarify to the community which they should use and in which situations? Or do they not use Resolutions at all as it's an SC-only vehicle (my preference)?

Aside from that, what's the list of outstanding tasks/questions until we can resolve this issue?

**Comment by anajsana** [comment]
> It looks like a great deal of work has been done on this already by the 2021 SC (thank you!).
> 
> My primary question here is how do Proposals differ from the already existing [Resolutions](https://github.com/todogroup/governance/blob/main/resolutions/README.md)? How do we clarify to the community which they should use and in which situations? Or do they not use Resolutions at all as it's an SC-only vehicle (my preference)?
> 
Didn't realize that we could use the [Resolutions](https://github.com/todogroup/governance/blob/main/resolutions/README.md) repo for that purpose, so thanks for the heads up! The initial plan was to use the proposal form anytime someone wants to make a proposal that does not fit in the existing TODO Strategic Goals.

Saying this, while I think the Resolution method is great to approve/decline Steering Committee & Project Management specific topics (e.g changes on the charter, propose new SC voting process or SC monthly meeting hours, and more) I think that it might be a complex method with too many steps to follow (copy the template, add it in a different folder, send a PR, etc) for those scenarios where the community simply want to notify a proposal related to new TODO initiatives (For instance: partnerships with other communities with specific outcomes, working groups which the main purpose is to work on initiatives that do not exist on TODO resources, feedback on existing TODO procedures).

That's why I [suggest creating a proposal issue form](https://github.com/todogroup/governance/pull/156), where the community can simply go to "create new issue" fill a form and send.

However, if the SC thinks that there is no need to create such form and that we can re-use the Resolution repo, then I would suggest refining its documentation or maybe finding a way to shorten the steps that a community participant should do to make a proposal.

> Aside from that, what's the list of outstanding tasks/questions until we can resolve this issue?

Based on my comment above, I'd suggest:

(1) Decide to either keep working on the proposal form (1.1) or discard it and work on the existing resolution repo (1.2)

* (1.1) If **keep working on the proposal form** then review [PR](https://github.com/todogroup/governance/pull/156) (by someone from SC), merge changes, and create necessary documentation

* (1.2) If **discard it and work on the existing resolution repo** then update [Resolution's README.md](https://github.com/todogroup/governance/blob/main/resolutions/README.md), send a PR with changes, review by the SC, and merge. I remember, that @justaugustus at some point suggested using the Discussions feature to let the community submit proposals, maybe that's something we can consider having in the Resolution repo (?)

**Comment by anajsana** [comment]
As agreed during the past SC Meeting, this new PR documents in the governance readme.md the steps to fill new proposals by the community and how the SC will review them via GH Discussions (under ospology repo): https://github.com/todogroup/governance/pull/225

**Comment by anajsana** [comment]
This is already implemented: https://github.com/todogroup/governance#-file-proposals-by-the-community

An email will be sent via TODO Mailing List to let the community know about this new documentation
