### ISSUE TITLE
Document role and expectations for LF PM Support

### ISSUE THREAD

**Issue by DuaneOBrien** [todogroup/governance#132]
Capturing comments by @anajsana from #104 

"I think we should be even more specific about Steering Committee's planning level and the process this would follow. For instance:

1) The Steering Committee should act on a strategic level: SC Members should define and approve a set of strategic goals for each year during the SC monthly meeting, that will be documented at: https://github.com/todogroup/governance/blob/master/goals.md

2) Program Manager should act on a tactical level: PM should evaluate those goals and define and execute initiatives aligned with the strategic goals for that year. Only if an initiative does not fit in any of the defined strategic goals, the initiative should be reviewed and approved by the SC.

3) SC should be informed and provide advice on existing and new initiatives that are aligned with the strategic goals during the SC meetings.

This approach would avoid clogging up the design and execution of new initiatives and keep the project moving forward under the SC strategic vision."

![todoplanninglevels](https://user-images.githubusercontent.com/43671777/141785623-e4c7c49d-2d93-4ccb-9e88-b01f18c1b3ad.png)

**Comment by anajsana** [comment]
I think things are more clear since we made the distinction between TODO SC goals and LF goals: https://github.com/todogroup/governance/blob/main/goals.md#proposed-2022 + Manage SC Review tasks using the Kanban board. 

I think we can close this task
