### ISSUE TITLE
Changes to SC election process for 2022

### ISSUE THREAD

**Issue by geekygirldawn** [todogroup/governance#150]
We got a late start on the election process this year, and I'd like to propose some other changes as well.

* For nominations, I would like for the nominee to provide some background information that is available for voters as they make their decision. Maybe things like: Bio / background. OSPO role. Why you are running for the SC. What you want to accomplish as part of the SC. This year, I felt like I was voting blind without enough understanding of people's motivations and skills.
* The charter states "nominations and voting during the month of September" for elections, so we should start talking about the process and what information we need from the nominees at the SC meetings in July / August.

**Comment by geekygirldawn** [comment]
We should also ask them to describe their previous contributions to the TODO Group.

**Comment by DuaneOBrien** [comment]
+1 to both of these suggestions.

**Comment by geekygirldawn** [comment]
I also think that next year we should wait to announce the results of the election until we can also announce the appointed folks. One announcement of the full SC would probably be better, since we sometimes nominate people who ran in the election. It also cuts down on email noise and potential confusion.

**Comment by anajsana** [comment]
> For nominations, I would like for the nominee to provide some background information that is available for voters as they make their decision. Maybe things like: Bio / background. OSPO role. Why you are running for the SC. What you want to accomplish as part of the SC. This year, I felt like I was voting blind without enough understanding of people's motivations and skills



> The charter states "nominations and voting during the month of September" for elections, so we should start talking about the process and what information we need from the nominees at the SC meetings in July / August.

LGTM. I've added an event at TODO Calendar for:

1) Start the SC Discussion (what info do the nominees need in order to participate, election days, etc) in the SC July monthly meeting 

2) Make sure to have everything ready by September

**Comment by vmbrasseur** [comment]
Hey there, team. Looks like there's been a merge on this issue. Is there any more work to be done or can we close it?

**Comment by vmbrasseur** [comment]
*nudge*

**Comment by justaugustus** [comment]
> Hey there, team. Looks like there's been a merge on this issue. Is there any more work to be done or can we close it?

@vmbrasseur -- https://github.com/todogroup/governance/pull/161 merged the waybackwhen content from https://github.com/todogroup/governance/pull/90, but does not include proposed changes from this issue.

Still on my plate! :)

**Comment by vmbrasseur** [comment]
Since the work's still in progress I'll move this issue to that column rather than Needs Review.

**Comment by anajsana** [comment]
This is already being done via: 
* https://github.com/todogroup/governance/issues/221
* https://github.com/todogroup/governance/issues/222

**Comment by anajsana** [comment]
This is already being done (see my last comment) Closing this issue 🙂
