### ISSUE TITLE
GitHub repository audit

### ISSUE THREAD

**Issue by justaugustus** [todogroup/governance#190]
Mentioned to the @todogroup/steering-committee and sort of related to https://github.com/todogroup/governance/issues/106...

We have too many repos to effectively manage; some that should be archived, some whose content may be better suited in more discoverable places.

Example from https://github.com/todogroup/todogroup.org/issues/266#issuecomment-1039596982:

> > Any thoughts on where it should go?
> 
> @justinabrahms @gyehuda @anajsana -- Maybe we expand https://todogroup.org/guides/ to include TIL (Today I Learned) quick tips?
> 
> I'm not seeing a place where we have content like this. In an ideal state, my internal documentation is just a bunch of links to TODO Group resources :)
> 
> Another thought is expanding guidance in https://github.com/todogroup/outbound-oss? Right now those docs are geared towards OSPO members, but adding a user/contributor persona may make sense.

Now that SC has magic powers on the org/the ability to discover all public and private repos, I'm planning to do an audit of the content and make some suggestions on how we can tidy up a little.

cc: @caniszczyk (as he may have thoughts/advice here)

**Comment by anajsana** [comment]
Thanks @justaugustus for creating this issue 🙌 TBH, I still discovering hidden outdated repos from the TODO GH org from time to time 😅

I guess this audit is expected to be done via zoom call. Do we want to either: 

* (1) Reserve some time in the upcoming SC meeting to work on this
* (2) Schedule a dedicated meeting to work on this 
* (3) Use the [March work day meeting](https://github.com/todogroup/work-day-activities#work-day-activity-tracker) to work on this

**Comment by jordanrule** [comment]
Just a perspective from my part of the country - most of the Kubernetes resources I've found here are managed by IBM and targeted towards enterprise governance and management.  If there are any Kubernetes resources dedicated more towards startup and community building, it would be helpful to make those more discoverable.

**Comment by anajsana** [comment]
Some updates from this issue:

* ✅ Completed repo audit for private repos
* TBD: work on public repo audit

**Comment by jordanrule** [comment]
Thank you @anajsana!  It has been awesome to see some movement on @todogroup.

**Comment by Relequestual** [comment]
Using the following classification systems might help group the repos but also help others know what state the repo is in.
https://www.repostatus.org
https://project-types.github.io

Both classification systems provide badges for readme files.
