### ISSUE TITLE
Proposal: New Repo Creation

### ISSUE THREAD

**Issue by anajsana** [todogroup/governance#199]
## Proposal

Create a new repo under TODO Group GH Org to allow people to contribute to this, and define a process and roadmap.

Asking for approval from @todogroup/steering-committee 

Related discussion: https://github.com/todogroup/ospology/discussions/75

**Comment by geekygirldawn** [comment]
I left a comment on #75 suggesting that we do this in a directory within an existing repo, instead of creating a new repo.

**Comment by anajsana** [comment]
Thanks for the review @geekygirldawn. Based on your comment, final resolution is:

* Don't create a new repo, but use existing one to host this. Most likely at 'ospology' repo

**Comment by justaugustus** [comment]
Closed with https://github.com/todogroup/ospology/discussions/75#discussioncomment-2461834 / https://github.com/todogroup/ospology/tree/main/ospo-mindmap.
