### ISSUE TITLE
[Strategic Goal] Determine the timeline for the surveys

### ISSUE THREAD

**Issue by anajsana** [todogroup/governance#206]
Define timeline and set up deadlines for each of the activities:

**General Member Survey**

* Define Questions
* Review Survey questionnaire
* Create a Form with the final version of the questionnaire 
* Form is Open
* Form is Closed
* Answers are reviewed by SC

**Community Survey**

* Define Questions
* Review Survey questionnaire
* Create a Form with the final version of the questionnaire 
* Form is Open
* Form is Closed
* Answers are reviewed by SC

**Comment by geekygirldawn** [comment]
In 2021, the member survey was open from December 7th through December 20th. I think maybe we should have them both open at the dame time, but do them earlier to avoid overlapping with the holidays.

Here's my proposed timeline - what do people think?

- September 1: Start project
  - September 1: begin working on defining questions  (see #207)
  - September 1: define plan for distributing and reminders for the survey (see #208)
- October 15: Questions defined for both surveys (see #207)
- October 26: SC & LF review of questions completed
- October 31: Create both forms with final version of questionnaires
- November 4: Steering committee approval of final questionnaires
- November 7: Survey forms opens
- November 7 and December 1: Distribute surveys and send reminders according to #208
- December 1: Survey forms closes
- December 1 - 9: Answers reviewed by Steering Committee & next steps determined

**Comment by anajsana** [comment]
Thanks for putting this together @geekygirldawn timeline works fine for my side 🙂 jus one question, the timeline you have proposed is for both surveys, right? (e.g when starting the "begin working on defining questions" task, we should work on questions for the GM and the Community survey at the same time)

**Comment by geekygirldawn** [comment]
Yes, exactly! I thought it would be easier to do both at the same time, since I'm guessing some of the questions will be the same or similar :)

**Comment by geekygirldawn** [comment]
@anajsana Just a quick reminder that we have Sept 1 on the timeline to start working on these surveys. Our deadline for having the list of Questions is Oct 15, so I think we have some time. Should we start working on the questions right after OSSummit?

**Comment by anajsana** [comment]
FYI : Starting a draft with the TODO Survey Questionnaire for 2022. I'll share via Steering Committee mailing list no later this week for review and additions 🙂 @geekygirldawn @vmbrasseur 

After reviewing previous surveys, I'm planning to do a single survey and add a small section for TODO General Members, instead of creating two different ones (community and general members). This way people don't get overwhelmed with so many surveys (e.g TODO Steering Committee elections, satisfaction surveys, etc). 

If you think we should do two separate surveys, please let me know!

**Comment by anajsana** [comment]
I've just shared via SC Mailing list the [draft for the TODO Satisfaction Questionnaire for 2022](https://docs.google.com/document/d/1x0GjskOtTq5zZp-8sjwzeigRkRuR0oxBsKK8r2I2imU/edit?usp=sharing). When ready, please interested people review and/or suggest changes in the document or leave feedback on this GH issue: https://github.com/todogroup/governance/issues/207

**Comment by geekygirldawn** [comment]
+1 to doing this is one survey.

My gut feel is that this is way too long, so before I provide detailed feedback on the questions, can you get some feedback from the survey experts within the LF / CNCF about how many questions are too many? Maybe there are some things they can suggest to streamline the survey? Or maybe this is fine, I'm just not sure?

**Comment by anajsana** [comment]
Thanks @geekygirldawn !

I don't have direct contact with survey experts within the LF / CNCF but I can ping @caniszczyk to [chime in](https://docs.google.com/document/d/1x0GjskOtTq5zZp-8sjwzeigRkRuR0oxBsKK8r2I2imU/edit?usp=sharing) 👍
