### ISSUE TITLE
Determine timeline for TODO Steering Committee 2023 nominations and elections

### ISSUE THREAD

**Issue by anajsana** [todogroup/governance#221]
This year the Steering Committee and TODO PM agreed to (1) start earlier the nomination and election process and (2) create a nomination survey (done via survey monkey) asking people interested to be elected to share their contributions to the community and bio info.

The proposed timeline is:

`July 1 - 30` Work on SC nomination form questionnaire and requisites to become an official candidate

* See https://github.com/todogroup/governance/issues/222

`Aug 1 - Sep 30` The nomination form opens

`Aug 1 - Sep 30` Distribute survey and send reminders

`Sep 30` The nomination form closes

`Oct 1`  Election poll opens

`Oct 1 - Oct 20` Distribute poll

`Oct 20` Election poll closes

`Oct 21` The new SC members for 2023 are announced

## Action items

- [ ] Review and approve the proposed timeline
- [x] Create necessary issues for timeline sections

**Comment by geekygirldawn** [comment]
This timeline looks good to me!

**Comment by anajsana** [comment]
> Looks good to me, just wondering how many of my fellow SC members will be on holiday in July.

I'll make sure to have the initial draft ASAP and have the SC to review, so it won't take a lot of your time 👍 🙂

**Comment by anajsana** [comment]
The timeline was approved by part of the SC, I'll close the issue and keep working on the following action items
