### ISSUE TITLE
Work on new SC nomination form questionnaire and requisites

### ISSUE THREAD

**Issue by anajsana** [todogroup/governance#222]
Create a nomination form where people can apply to become a TODO SC 2023 candidate. This questionnaire should gather info about:

* Contributions to the TODO Community
* OSPO experience
* Why applying to become an SC Candidate
* Bio and main role

The draft will be created via g.doc and reviewed by TODO SC. once approved, the content will be placed in a new TODO Survey Monkey form.

**Comment by anajsana** [comment]
Created the g.doc to work on the [2023 SC Nomination Questionnaire](https://docs.google.com/document/d/1YJcx8BMPIirTLgGTXDzW7mrPxo4RBNkppq2z-Z_9SKg/edit?usp=sharing) related to the issue. SC please review it prior to creating the survey form.
People can check SC Elections timeline at: https://github.com/todogroup/governance/issues/221

**Comment by vmbrasseur** [comment]
I've made some minor suggested edits to the questionnaire doc.

**Comment by anajsana** [comment]
The form is already published. closing this issue
