### ISSUE TITLE
Structure document could use some links

### ISSUE THREAD

**Issue by Relequestual** [todogroup/governance#248]
The structure document and mindmap is nice, but... I can't DO much having looked at it.
As a newcomer, I might know what maybe half of those items in the list are about.
I think MOST of them could be linked to other places to find out more about that specific item.

For example, linking out to where I can find details about the listed meetings would be great!

**Comment by anajsana** [comment]
Thanks for the feedback @Relequestual ! A quick solution I'm planning to do as an update is to add links to the existing markdown that shows in the doc. I'll let you know once the PR is made 👍

**Comment by anajsana** [comment]
@Relequestual I've added the missing links to the .md file: https://github.com/todogroup/governance/pull/257

Closing this issue from now. If something is missing, please don't hesitate to open a new issue! Thank you!
