### ISSUE TITLE
Audit TODO Slack channels and archive innactive ones

### ISSUE THREAD

**Issue by anajsana** [todogroup/governance#256]
TODO Slack has 35 channels created, but many of them have been inactive in the past 3 months (or even more). I'd like to review the `#topic-` related channels. Not many people use them and IMHO, they only add more complexity to TODO slack navigation.

My proposal is:

* Review existing TODO slack channels and look for duplicated ones
* Examine `#topics-` channels
   * If a topic has been inactive over the past 3 months, then archive
   * Before archiving a channel, write the reason why and remind members that they can suggest re-opening it by submitting a community proposal via GH Discussions (ospology repo), anytime

> PS: In the near future, maybe the #topic- channels can be converted into `#wg-` channels

**Comment by vmbrasseur** [comment]
This is a great plan. I'm totally on board!

**Comment by vmbrasseur** [comment]
I should've included: How can we help?

**Comment by anajsana** [comment]
Thanks for offering your help @vmbrasseur ! I think that this ticket is related to the goal defined as *"creating documentation to specify how / when /where to shut down inactive initiatives in TODO"* and @tsteenbe issue: https://github.com/todogroup/governance/issues/261

I think having your input on what items should this document have, and the best places to be added (e.g governance repo / website) would be very valuable. This way, I can have some guidelines to create the initial draft and send a PR for review.

**Comment by annania** [comment]
Sounds like a plan!

**Comment by lhawthorn** [comment]
Sounds good to me!

**Comment by anajsana** [comment]
this process has been already implemented. if a channel is inactive for more than 3months in Slack, a warning is sent to the channel, if the inactivity continues, the channel is archived with a notice
