### ISSUE TITLE
Steering Committee Chair

### ISSUE THREAD

**Issue by vmbrasseur** [todogroup/governance#258]
Section 4 of the charter reads:

> Officers of The Steering Committee shall elect a Chairperson, and if so desired, may elect such other officers as it may choose. All officers shall be elected annually. There are no limits on the number of terms an officer may serve.

I see two problems here:

1. Nowhere in the charter does it list the roles/responsibilities of the chair, only that the role shall be elected.
2. To the best of my knowledge, the Steering Committee has never done this? Or at least not in a long time? But that "shall" means that doing so is required.

I suggest that the SC discuss this at their next call. We should determine whether we want to be required to have a chair (as is currently documented in the charter) and, if we do, what the roles/responsibilities are for that person. Also, if we do want a chair, we shouldn't elect one until we set those expectations for the role so candidates know what they might be getting into.

**Comment by anajsana** [comment]
I've added to the Jan SC agenda for further discussion!

**Comment by anajsana** [comment]
Related PR #255
