### ISSUE TITLE
[Call For Input] 2023 TODOStrategic Goals

### ISSUE THREAD

**Issue by anajsana** [todogroup/governance#262]
The TODO Steering Committee is working on defining the 2023 Strategic Goals to align with the project mission and community needs. This year, we aim to use this issue as the main channel to gather feedback on the [proposed 2023 goals](https://github.com/todogroup/governance/blob/main/goals.md#-proposed-2023).

## 🙋‍♀️ Who we want to hear from

* OSPO practitioners and TODO General Members
* Contributors involved in TODO and/or OSPOlogy
* Local OSPO Communities (Europe, Asia, Africa, Oceania, America, etc)
* Outside open source organizations and broader Linux Foundation projects

## 🗳 Next steps

If you would like to take part, please follow these steps:

### Provide new ideas (Requirements)

1. Read the [proposed goals for 2023](https://github.com/todogroup/governance/blob/main/goals.md#-proposed-2023) and the [achieved goals in 2022](https://todogroup.org/blog/a-year-in-review-2022/).
2. Make sure the idea is aligned with TODO pillars:
    - Cultivate education and adoption of OSPOs worldwide
    - Grow the global and local community
    - Create value for community participants and general members
3. Leave a comment on this issue and document: 
     - Your relationship to OSPOs (end-user, vendor, student)
     - Your relationship with TODO Community (active OSPOlogy contributor, TODO general member, OSPO Associate, etc)
     - The scope/problem
     - The goal theme, title, and possible next steps (suggested actions to achieve the goal)
     - How this idea would benefit the OSPO ecosystem
     - Level of commitment to work on this goal (leading position, active participation, no time for commitment, etc)

### Give support to an existing idea (Requirements)

* Please give a 👍 (thumbs up) to the comment that you'd like to support

## ⚠️ Deadline 

This issue will be closed on February 1st at 12:00pm (UTC). During that day the TODO SC will meet to define the final version of 2023 TODO Strategic Goals based on the input provided and available time and resources

**Comment by anajsana** [comment]
Input gathered in the last Touchpoint GM meeting (EMEA & APAC) - Thus 19 2023 call

**Support local working groups to foster the following activities:**
* Gather case studies on how to build OSPOs for local markets where OSPOs are not generally present
* Gather case studies on how to negotiate with management 

**Secure OSS and sustainability with OSPOs** 
* Initiate new working group (Can fit in the Working Group Goal)
* Bring awareness to companies and OSPOs
* Might fit to “create value” topic

**Comment by caabernathy** [comment]
Cultivate relationships with other communities:

- Industry / University - Buddy program to help up and coming OSPO
- OpenSSF and OSPOs - collaboration / working group
