### ISSUE TITLE
Inconsistent Slack invite links

### ISSUE THREAD

**Issue by lelia** [todogroup/governance#287]
The [onboarding issue template](https://github.com/todogroup/governance/blob/main/.github/ISSUE_TEMPLATE/onboarding-general-member.md) for new general members has a broken signup link for the TODOGroup Slack: https://slack.todogroup.org

In comparing all `'Slack'` references in the repository, I found that some docs are using [the same link](https://slack.todogroup.org), while others are using a [longform invite link](https://join.slack.com/t/thetodogroup/shared_invite/zt-169ok18cz-Pi6tpVHTeW9254d1FpkLew) (which _does_ work): 

* [onboarding-general-member.md](https://github.com/todogroup/governance/blob/main/.github/ISSUE_TEMPLATE/onboarding-general-member.md?plain=1#L40) (**broken link**)
* [structure-mindmap.md](https://github.com/todogroup/governance/blob/main/TODO%20Structure/structure-mindmap.md?plain=1#L29) (working link)
* [general-member.md](https://github.com/todogroup/governance/blob/main/onboarding/general-member.md?plain=1#L66) (**broken link**)
* [community.md](https://github.com/todogroup/governance/blob/main/onboarding/community.md?plain=1#L63) (working link)

Happy to file a PR to fix, just need to know which link should be used as a replacement! 🙂

**Comment by anajsana** [comment]
Thanks for raising this issue @lelia ! Here are the fixed links:

* [onboarding-general-member.md](https://github.com/todogroup/governance/blob/main/.github/ISSUE_TEMPLATE/onboarding-general-member.md?plain=1#L40) |  [fixed link](https://join.slack.com/t/thetodogroup/shared_invite/zt-169ok18cz-Pi6tpVHTeW9254d1FpkLew)

* [general-member.md](https://github.com/todogroup/governance/blob/main/onboarding/general-member.md?plain=1#L66) |  [fixed link](https://join.slack.com/t/thetodogroup/shared_invite/zt-169ok18cz-Pi6tpVHTeW9254d1FpkLew)

If you submit a PR with the changes, we will make sure to merge it ASAP! Thank you 🙏
