### ISSUE TITLE
Configure gitvote

### ISSUE THREAD

**Issue by justaugustus** [todogroup/governance#326]
- [x] App installation completed: https://github.com/organizations/todogroup/settings/installations/50022891
- [x] [GitVote](https://github.com/cncf/gitvote) setup on todogroup/governance repo
  - [x] Add configuration file ([ref](https://github.com/cncf/gitvote/blob/main/docs/config/.gitvote.yml)): https://github.com/todogroup/governance/pull/327
  - [x] Fix teams configuration: https://github.com/todogroup/governance/pull/328
  - [x] Do not exclude team maintainers from voting: https://github.com/todogroup/governance/pull/329
  - [ ] Update pass threshold to simple majority (51%): https://github.com/todogroup/governance/pull/330
- [ ] (BONUS) .github repo rollout?

cc: @anajsana

**Comment by justaugustus** [comment]
Testing gitvote, now that https://github.com/todogroup/governance/pull/327 has merged:
/vote

**Comment by justaugustus** [comment]
Merged https://github.com/todogroup/governance/pull/328 to fix https://github.com/todogroup/governance/issues/326#issuecomment-2080407187.

Let's try this again...
/vote

**Comment by justaugustus** [comment]
The `/check-vote` has [results I was not expecting](https://github.com/todogroup/governance/issues/326#issuecomment-2080409732):

<img width="913" alt="Screenshot 2024-04-27 at 04 09 51" src="https://github.com/todogroup/governance/assets/567897/4b01e68b-4a70-4eb8-b791-869cc93f0873">

- I was not recognized as a binding vote
- The `Not Voted` column expects 4 voters, though the membership count of @todogroup/gitvote-steering is currently 6, which means it's also excluded @ashleywolf

### Why this is happening

If you look at team membership, you'll notice that Ashley and I are listed as maintainers, not members:

<img width="1512" alt="Screenshot 2024-04-27 at 04 14 25" src="https://github.com/todogroup/governance/assets/567897/0958d497-03ad-40d0-8479-7ccc735b32e7">
<img width="1512" alt="Screenshot 2024-04-27 at 04 14 45" src="https://github.com/todogroup/governance/assets/567897/0674a34e-8ab6-4df9-b038-42f4f998261a">
<img width="1512" alt="Screenshot 2024-04-27 at 04 15 02" src="https://github.com/todogroup/governance/assets/567897/b2bb17e1-22fe-4e7f-8dc1-fd655fdd9335">

If we look at org membership, you'll see that Ashley and I are the only Steering Committee members that are also organization owners:

<img width="1510" alt="Screenshot 2024-04-27 at 04 17 03" src="https://github.com/todogroup/governance/assets/567897/b2124cbc-3508-45dc-b246-2f2cc5936e39">
<img width="1512" alt="Screenshot 2024-04-27 at 04 17 24" src="https://github.com/todogroup/governance/assets/567897/1f54c792-e0ff-4bdc-8dbd-71d178e19e86">

I'll discuss this cleanup separately, and in the context of https://github.com/todogroup/governance/issues/106, but will push a fix to the gitvote shortly.

**Comment by justaugustus** [comment]
Retrying the vote, now that https://github.com/todogroup/governance/pull/329 has merged:
/vote

**Comment by justaugustus** [comment]
Ashley and I are included as binding with that config fix!

<img width="917" alt="Screenshot 2024-04-27 at 04 37 43" src="https://github.com/todogroup/governance/assets/567897/d64b430e-0c39-4a4f-a136-73e5857af5e5">

**Comment by gkunz** [comment]
> Votes can only be checked once a day.

lazy bot! 🤖

**Comment by justaugustus** [comment]
Updating the pass threshold to simple majority (51%) will close this issue out: https://github.com/todogroup/governance/pull/330

**Comment by lhawthorn** [comment]
Sorry to be late to the party. Do we want to reopen the vote and I can confirm whether my vote is counted and viewed as binding/non-binding?

**Comment by justaugustus** [comment]
@lhawthorn — sure, a quick check would be good!

/vote

**Comment by lhawthorn** [comment]
Done.

**Comment by justaugustus** [comment]
Thanks Leslie!
Validated that your vote is counted as binding now.
<img width="930" alt="Screenshot 2024-05-17 at 02 22 12" src="https://github.com/todogroup/governance/assets/567897/0f68c3f2-8d1e-41a4-afb4-11c6ab1dda3e">

/cancel-vote
