### ISSUE TITLE
Update resolution template to include new Steering Committee members.

### ISSUE THREAD

**Issue by DuaneOBrien** [todogroup/governance#73]
The default resolution template contains a list of Steering Committee members that needs to be updated whenever there is a SC membership change. We need to update the current one, but should make sure we have a process in place to update this template whenever there is a SC membership change, or remove the hard-coded list of SC members.

**Comment by vmbrasseur** [comment]
This probably should be part of a general "things to do when there's an SC membership change" playbook, which doesn't exist but probably ought to. I doubt that template is the only thing that'll need updating.
