### ISSUE TITLE
Possible charter charge: remove calendar month requirement for Steering Committee 

### ISSUE THREAD

**Issue by amye** [todogroup/governance#80]
Currently, the [charter](https://github.com/todogroup/governance/blob/master/CHARTER.adoc) reads as follows: 

"In each calendar year, the group shall hold an election to fill elected positions which will be vacated at the end of that year. The election process shall include nominations and voting during the month of September."

Terms begin January 1, so it might make sense to remove the calendar month requirement.

**Comment by kpfleming** [comment]
I'm a fan of structure, so I'm not sure I'd like to have it left open-ended.

**Comment by jeffmcaffer** [comment]
+1 on having structure. means we only have the "when to run the voting" discussion once (now/here) rather than every year. If we want to address the time gap between voting and taking up the role, we could move from Sept to Oct, Nov, or Dec. IMO moving to Oct would be fine. Later than that and we start getting into holidays etc. and everyone being busy.

**Comment by alolita** [comment]
+1 for maintaining a regular cadence for governance /election process. We
could be somewhat loose in saying a review of upcoming seats and voting
will be conducted in Q4 every year by no later than November 15th.

Best,
Alolita

**Comment by vmbrasseur** [comment]
+1 to retaining structure. Also +1, though, to shifting the elections closer to the end of the year. A September/October election for people who don't take their seats until January is too large of a gap.

While I somewhat agree that we should avoid holidays if possible, I'm not sure that will actually matter very much in practice. My suspicion is that we have relatively poor voter turnout as-is, and the people who vote will vote regardless if given enough time and reminders to do so. The remainder are currently unlikely to vote at all (a separate issue to look at). At least that's my impression. So I think moving nominations to October with elections in November would probably accomplish what we need without hitting too many holiday conflicts or other negative effects.

If we want to make a change to the charter, it doesn't look like it needs a resolution:

> This Charter may be amended, and additional rules may be adopted, at any time by a two-thirds majority of all then serving Steering Committee members with final approval from The Linux Foundation.

**Comment by anajsana** [comment]
Outdated issue. I suggest to close all old issues related to making changes to TODO Charter and if needed, open new ones based on current needs on 2023, aligning with the new SC.
