### ISSUE TITLE
Create "new SC member(s) playbook"

### ISSUE THREAD

**Issue by vmbrasseur** [todogroup/governance#81]
Per a comment on #73, we should create a basic playbook for the things to do when we have one or more new members of the steering committee.

Maybe create this as an issue template, so we can quickly/easily create an issue for tracking this work when we have SC member churn?

**Comment by vmbrasseur** [comment]
Courtesy of @decause, an example of [issue templates](https://github.com/spotify/backstage/tree/master/.github/ISSUE_TEMPLATE).

**Comment by vmbrasseur** [comment]
This issue will require two PRs, I suspect. The first one will add an issue template, and after it's merged the second one will update the README to point to the correct 'new issue + template' link. (it's just a minor pain to figure out that link in advance, is all).

**Comment by justaugustus** [comment]
Issue template was created in https://github.com/todogroup/governance/pull/84 and has more recent updates [here](https://github.com/todogroup/governance/pull/153), so I think this can be closed.
