### ISSUE TITLE
Update docs for decision making process

### ISSUE THREAD

**Issue by vmbrasseur** [todogroup/governance#93]
Thanks to #90, we discovered that we can do better on documenting how we make decisions. What we decided:

* For things that require doc changes (charter included), send a PR w/proposed changes. All discussions about the change occur on the PR. All steering committee votes on the change also occur on the PR in the form of +1s.
* The formal change requires a resolution according to the already documented progress. For a change that has a PR, the resolution should be a part of that PR and reference the git hash of the approved change. The steering committee then gets a heads up to review/approve this resolution and everything proceeds according to the usual resolution process.
* Generally speaking, all governance-related decisions require a resolution. This ensures that decisions are documented and in version control but are not tied to the UI of a single vendor (GitHub in this case).

We need to make sure that we update all documentation to be really clear about all ^^ that stuff. It will probably require updating a few different files to ensure that it's covered, or at least checking a few different files to verify whether changes are needed.

I don't have the cycles for that right now but can hopefully carve some out during our next GitHub Workday (currently scheduled for December 11).

**Comment by anajsana** [comment]
This can be documented also in the TODO Playbook (issue related #283 )

**Comment by Relequestual** [comment]
Markdown Any Decision Records gives a nice approach to documenting decisions: https://adr.github.io/madr/
Previously ADR meant Architecture Decision Record, but it has now been upgraded to "Any"!

**Comment by anajsana** [comment]
This is an old issue which has been updated to https://github.com/todogroup/governance/issues/307
